## One Hot Encoding

Es un proceso mediante el cual las variables categóricas se convierten en una forma que podría proporcionarse a los algoritmos de ML para hacer un mejor trabajo en la predicción.

In [1]:
import pandas as pd


In [2]:
df = pd.read_csv(r'https://raw.githubusercontent.com/Lawlesscodelen/thebridge_ds/master/data/titanic.csv')

In [3]:
df.shape #vemos cuántas filas y columnas 

(891, 12)

In [4]:
df.columns #Vemos las columnas 


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df.isna().sum() #vemos donde hay NAS

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
df = df.loc[df.Embarked.notna(), ['Survived','Pclass', 'Sex', 'Embarked']] #Nos quedamos con cuatro columnas 

In [6]:
df.shape

(889, 4)

In [7]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Embarked    0
dtype: int64

In [8]:
df.head()

Survived  Pclass     Sex Embarked
0         0       3    male        S
1         1       1  female        C
2         1       3  female        S
3         1       1  female        S
4         0       3    male        S

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
ohe = OneHotEncoder(sparse=False) # Objeto sparse, para que no salga una matriz de ceros
#OneHotEncoder(sparse=True).fit_transform(df[['Sex']])

In [12]:
ohe.fit_transform(df[['Sex']]) #numpy array with two columns

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [13]:
ohe.categories_

[array(['female', 'male'], dtype=object)]

In [14]:
ohe.fit_transform(df[['Embarked']])#Numpy array with three columns 

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [15]:
ohe.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [16]:
from sklearn.compose import make_column_transformer

In [17]:
column_trans = make_column_transformer(
(OneHotEncoder(), ['Embarked', 'Sex']),
    remainder = 'passthrough')

In [18]:
array = column_trans.fit_transform(df)
array

array([[0., 0., 1., ..., 1., 0., 3.],
       [1., 0., 0., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 3.],
       ...,
       [0., 0., 1., ..., 0., 0., 3.],
       [1., 0., 0., ..., 1., 1., 1.],
       [0., 1., 0., ..., 1., 0., 3.]])

In [19]:
name_columns = ['Embarked_C', 'Embarked_Q', 'Embarked_S', 'Sex_female', 'Sex_male', 'Survived','PClass']
nf = pd.DataFrame(data=array, columns=name_columns)
nf

Embarked_C  Embarked_Q  Embarked_S  Sex_female  Sex_male  Survived  \
0           0.0         0.0         1.0         0.0       1.0       0.0   
1           1.0         0.0         0.0         1.0       0.0       1.0   
2           0.0         0.0         1.0         1.0       0.0       1.0   
3           0.0         0.0         1.0         1.0       0.0       1.0   
4           0.0         0.0         1.0         0.0       1.0       0.0   
..          ...         ...         ...         ...       ...       ...   
884         0.0         0.0         1.0         0.0       1.0       0.0   
885         0.0         0.0         1.0         1.0       0.0       1.0   
886         0.0         0.0         1.0         1.0       0.0       0.0   
887         1.0         0.0         0.0         0.0       1.0       1.0   
888         0.0         1.0         0.0         0.0       1.0       0.0   

     PClass  
0       3.0  
1       1.0  
2       3.0  
3       1.0  
4       3.0  
..      ...  
884     2.0  
885     1.0  
886     3.0  
887     1.0  
888     3.0  

[889 rows x 7 columns]